apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-shortner
spec:
  replicas: 2
  selector:
    matchLabels:
      app: url-shortner
  template:
    metadata:
      labels:
        app: url-shortner
    spec:
      containers:
      - name: url-shortner
        image: url-shortner:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"

        env:
        - name: DB_HOST
          value: mysql
        - name: REDIS_ADDR
          value: redis:6379