name: Semantic Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get latest version
        id: get_tag
        run: |
          TAG=$(git tag --sort=-v:refname | head -n 1)

          if [ -z "$TAG" ]; then
            TAG="v1.0.0"
          else
            VERSION=${TAG#v}
            IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
            PATCH=$((PATCH+1))
            TAG="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Create Tag
        run: |
          git tag ${{ steps.get_tag.outputs.tag }}
          git push origin ${{ steps.get_tag.outputs.tag }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.get_tag.outputs.tag }}
          name: ${{ steps.get_tag.outputs.tag }}
          generate_release_notes: true